import pytest

from pipeline.state import PipelineState


@pytest.fixture
def mock_state_001() -> PipelineState:
    return {
        "loan_id": "LOAN_001",
        "los_data": {
            "loan_id": "LOAN_001",
            "applicant_name": "Rajesh Sharma",
            "loan_amount": 500000.0,
            "funding_amount": 500000.0,
            "applicant_mobile_no": "9876543210",
            "applicant_dob": "1990-05-15",
            "applicant_pan_number": "ABCDE1234F",
            "fathers_name": "Suresh Sharma",
            "applicant_bank_account_no": "987654321012",
            "loan_type": "Personal Loan",
            "loan_validity": "24 months",
            "current_address": "123 MG Road, Bengaluru, Karnataka, 560001",
            "permanent_address": "123 MG Road, Bengaluru, Karnataka, 560001",
            "aadhaar_no": "123456789012",
            "application_date": "2024-01-10",
            "bank_account_type": "Savings",
            "applicant_gender": "Male",
            "login_date": "2024-01-11",
            "disbursement_date": "2024-01-15",
            "tenure_months": 24,
            "application_id": "LOAN_001",
            "pan": "ABCDE1234F",
        },
        "raw_doc_paths": {},
        "extracted_data": {
            "aadhaar": {
                "applicant_name": "Rajesh Sharma",
                "address": "123 MG Road, Bengaluru, Karnataka, 560001",
                "aadhaar_number": "123456789012",
                "mobile_no": "9876543210",
                "dob": "1990-05-15",
            },
            "pan": {
                "applicant_name": "Rajesh Sharma",
                "fathers_name": "Suresh Sharma",
                "pan_number": "ABCDE1234F",
                "dob": "1990-05-15",
            },
            "application_form": {
                "applicant_name": "Rajesh Sharma",
                "fathers_name": "Suresh Sharma",
                "dob": "1990-05-15",
                "mobile_no": "9876543210",
                "gender": "Male",
                "pan_number": "ABCDE1234F",
                "loan_amount": "500000",
                "loan_validity": "24 months",
                "account_no": "987654321012",
                "type_of_account": "Savings",
                "loan_type": "Personal Loan",
                "current_address": "123 MG Road, Bengaluru, Karnataka, 560001",
                "application_date": "2024-01-10",
                "application_no": "LOAN_001",
                "login_date": "2024-01-11",
                "disbursement_date": "2024-01-15",
                "tenure_months": 24,
                "address_text": "123 MG Road, Bengaluru, Karnataka, 560001",
                "application_id": "LOAN_001",
            },
            "account_statement": {
                "applicant_name": "Rajesh Sharma",
                "pan_number": "ABCDE1234F",
                "mobile_no": "9876543210",
                "account_no": "987654321012",
            },
            "loan_agreement": {"loan_amount": 500000.0, "tenure_months": 24},
            "kfs": {
                "loan_amount": 500000.0,
                "funding_amount": 500000.0,
                "loan_validity": "24 months",
                "loan_type": "Personal Loan",
                "loan_account_no": "LOAN_001",
                "customer_consent": True,
                "bpi_charge": 1500.0,
                "broken_period_interest": 1500.0,
            },
            "sanction_letter": {
                "applicant_name": "Rajesh Sharma",
                "loan_amount": 500000.0,
                "funding_amount": 500000.0,
                "tenure_months": 24,
                "broken_period_interest": 1500.0,
            },
            "kyc_pan": {"pan_number": "ABCDE1234F", "name": "Rajesh Sharma"},
            "kyc_address_proof": {"address_text": "123 MG Road, Bengaluru, Karnataka, 560001"},
            "disbursal_memo": {
                "loan_no": "LOAN_001",
                "loan_amount": 490000.0,
                "bpi_charge": 1500.0,
                "application_id": "LOAN_001",
                "closure_id": "CLOSURE_8877",
                "disbursal_amount": 490000.0,
            },
        },
        "face_embeddings": {
            "selfie_vector": [0.1] * 128,
            "application_form_photo_vector": [0.101] * 128,
        },
        "dms_status": {"aadhaar_xml": {"exists": True}},
        "otp_audit": {"otp_verified": True},
        "comparison_results": [],
        "subnode_rollups": {},
        "compiled_report": {},
        "scorecard": {},
        "retry_count": 0,
        "checker_result": {},
        "errors": [],
        "node_history": [],
    }

