apiVersion: v1
kind: Service
metadata:
  name: {{ include "dgcl.fullname" . }}-api
  labels:
    {{- include "dgcl.selectorLabels" (merge (dict "component" "api") .) | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "dgcl.selectorLabels" (merge (dict "component" "api") .) | nindent 4 }}
  ports:
    - name: http
      port: 8000
      targetPort: http
      {{- if and (eq .Values.api.service.type "NodePort") .Values.api.service.nodePort }}
      nodePort: {{ .Values.api.service.nodePort }}
      {{- end }}
---
{{- if .Values.api.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "dgcl.fullname" . }}-api
  labels:
    {{- include "dgcl.selectorLabels" (merge (dict "component" "api") .) | nindent 4 }}
spec:
  minAvailable: {{ .Values.api.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "dgcl.selectorLabels" (merge (dict "component" "api") .) | nindent 6 }}
{{- end }}
---
{{- if .Values.api.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "dgcl.fullname" . }}-api
  labels:
    {{- include "dgcl.selectorLabels" (merge (dict "component" "api") .) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "dgcl.fullname" . }}-api
  minReplicas: {{ .Values.api.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.api.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.api.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
