{{- if .Values.sharedStorage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dgcl.fullname" . }}-shared-poc-data
  labels:
    {{- include "dgcl.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  {{- if .Values.sharedStorage.storageClassName }}
  storageClassName: {{ .Values.sharedStorage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.sharedStorage.size }}
{{- end }}
